# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
